### ISSUE TITLE
Sharing with Spatial Mapping Tap to Place

### ISSUE THREAD

**Issue by reillydonovan** [mtaulty/HLSharing#1]
Hi Mike, Reilly here, I'm a new media artist in Seattle, WA USA.  I've been following your blog posts concerning the hololens and have found them very helpful, thank you for all of your published work.  I have a quick question about the sharing tutorial you've provided- is there a quick way to apply the shared transforms to the tap to place script by changing something in the scripts you've provided?  I'm still having difficulty wrapping my head around how the whole sync system works, but I'll keep at it until I get it!  Thanks again for your help, cheers~

-Reilly

**Comment by mtaulty** [comment]
Hi - drop me a mail at mtaulty at microsoft dot com and we can hopefully work it out :-)

**Comment by cookiedancer** [comment]
Hi Mike,  just noticed this post.
Thanks for all the tutorials at your blog.  I also found the sharing tutorial very helpful.  I am developing a small prototype for a dental college in Nashville, TN and was able to implement a small sharing demonstration using the Tap to Place script. 

Here are two links to the implementation:
Shows Sharing Message Output
[](https://drive.google.com/open?id=0B01rMfZ-W8x0Y29UbE1oazBCX00)

Sharing Menu with Your Avatar
[](https://drive.google.com/open?id=0B01rMfZ-W8x0dmR3TlBtZW5CRzA)

Thanks again!
Best,
Thelma

**Comment by cookiedancer** [comment]
Mike, Sorry, links did not display with last comment. here they are: 
Show Sharing Message Output:
https://drive.google.com/open?id=0B01rMfZ-W8x0Y29UbE1oazBCX00

Sharing Menu with Your Avatar
https://drive.google.com/open?id=0B01rMfZ-W8x0dmR3TlBtZW5CRzA

Best,
Thelma
